blog/urls.py
from django.urls import path
from . import views, blogs
from .views import PostIndexView, PostDetailView, VisitorDetailView, VisitorListView, PostEditView, HomeLoginView
from .blogs import BlogListView

# Debug logging only
import logging
logger = logging.getLogger(__name__)

app_name = 'blog'

urlpatterns = [
    path('index/<slug:slug>/', views.PostIndexView.as_view(query_status='published'), name='index'),
    path('index/draft/<slug:slug>/', views.PostIndexView.as_view(query_status='draft'), name='index-draft'),
    path('index/deleted/<slug:slug>/', views.PostIndexView.as_view(query_status='deleted'), name='index-deleted'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/', PostDetailView.as_view(), name='detail'),
    path('visitor/<int:pk>', VisitorDetailView.as_view(), name='visitor'),
    path('<int:post_id>/share/', views.share, name='share'),
    path('visitor_query/', views.visitor_query, name='visitor-query'),
    path('avatar_select/<str:file>', views.avatar_select, name='avatar-select'),
    path('delete_comment/<int:pk>', views.delete_comment, name='delete_comment'),
    path('approve_comment/<int:pk>', views.approve_comment, name='approve_comment'),
    path('move_post_to/<int:post_id>/<int:blog_id>', views.move_post_to, name='move_post_to'),
    path('set_status/<int:post_id>/<str:new_status>', views.set_status, name='set_status'),
    path('visitor_list/', views.VisitorListView.as_view(), name='visitor-list'),
    path('edit_post/<int:pk>', PostEditView.as_view(), name='edit-post'),
    path('get_preview/', views.get_preview, name='get-preview'),
    path('like/', views.like_comment, name='like'),
    path('blog_list/', blogs.BlogListView.as_view(), name='blog-list'),
    path('home/', HomeLoginView.as_view(), name='home')
]

microsnout/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import TemplateView, RedirectView

urlpatterns = [
    path('', RedirectView.as_view( url=reverse_lazy('blog:home') )),
    path('blog/', include('blog.urls', namespace='blog')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block html_title %}{% endblock %}</title>
        <link href="{% static "css/bulma.min.css" %}" rel="stylesheet">
        <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}">
        <style>
            .bg-modal {
                width: 100%;
                height: 100%;
                background-color: rgba(0,0,0,0.25);
                position: absolute;
                top: 0px;
                z-index: 1;
                justify-content: center;
                align-items: center;
            }

            {% if modal %}
            .bg-modal { display: flex; }
            {% else %}
            .bg-modal { display: none; }
            {% endif %}

            .bg-content {
                background-color: #f0f0f0;
                border: none;
                border-radius: 15px;
                padding: 15px;
                position: relative;
            }

            .navbar-dropdown a,
            .dropdown-menu a {
                font-size: 10px;
                font-weight: 700;
                padding-top: 0.25rem;
                padding-bottom: 0.25rem;
            }
        </style>
        <script src="{% static 'js/jquery-3.5.1.js' %}"></script>
        {% block style %}
        {% endblock style %}
        {% block script %}
        {% endblock script %}
    </head>
    <body>
        {% if user.is_authenticated %}
        <p class="mx-2 my-0 py-0" style="text-align: right; font-size: 12px;">
            <a class="has-text-link mx-2" href="{% url 'logout' %}">Logout</a>
            User: <strong>{{ user.username }}</strong>
        </p> 
        {% endif %}
        {% if not post.banner %}
        <section class="hero is-info">
            <div class="hero-body">
                <div class="container">
                <h1 class="title">
                {% block title %}
                {% endblock title %}
                </h1>
                <h2 class="subtitle">
                {% block subtitle %}
                {% endblock subtitle %}
                </h2>
                </div>
            </div>
        </section>
        {% endif %}
        <nav class="navbar is-transparent has-background-info" role="navigation" aria-label="main navigation">
            <div class="navbar-menu is-active">
                <div class="navbar-start">
                    <a class="navbar-item has-text-white" href="{% url 'blog:home' %}"> Home </a>
                    <a class="navbar-item has-text-white" href="{{ blog.get_absolute_url }}"> Cover </a>
                    {% if user.is_staff %}
                    <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-item has-text-white px-2">&laquo;Admin&raquo;</a>
                        <div class="navbar-dropdown">
                            <p class="pl-2 is-size-7 has-text-weight-bold">Goto:</p>
                            <a class="dropdown-item" href="/admin">Django Admin</a>
                            <a class="dropdown-item" href="{% url 'blog:blog-list' %}">Blog Management</a>
                            <a class="dropdown-item" href="{% url 'blog:visitor-list' %}">Visitor Management</a>
                            {% if blogs %}
                            <hr class="dropdown-divider">
                            <p class="pl-2 is-size-7 has-text-weight-bold">Goto blog:</p>
                                {% for blog in blogs %}
                                    <a href="{% url 'blog:index' slug=blog.slug %}" class="dropdown-item">
                                        &ldquo;{{ blog.title|truncatechars:28 }}&rdquo;
                                    </a>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
            {% block navbar %}
            {% endblock navbar %}
        </nav>    

        <section class="section py-2">
            <div class="columns">
                <div class="column is-four-fiths">
                {% block main %}
                {% endblock main %}
                </div>
                <div class="column is-one-fifth" >
                    <div id="recent-posts" class="box">
                    {% block sidebar %}
                    {% endblock sidebar %}
                    </div>
                </div>
            </div>
            {% block lower %}
            {% endblock lower %}
        </section>

        <footer class="footer has-background-info">
            <div class="content has-text-centered has-text-white">
                <p>Microsnout 2020</p>
            </div>
        </footer>

        {% block heel %}
        {% endblock heel %}
    </body>
</html